# Dependencies
# markdown格式
markdown:         redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter:      pygments

# Permalinks 部落格文章網址的顯示方式
# date     /:categories/:year/:month/:day/:title.html
# pretty   /:categories/:year/:month/:day/:title/
# none     /:categories/:title.httpsml
permalink:        pretty
relative_permalinks: true

# Setup
title:            '程式是條不歸路'
#tagline:
description:      'Saying "Life is what we make it to be", is like saying "Language is what we make it to be" — True but not at once; — just one bit at a time.'
url:              http://azi.github.io
baseurl:          /

author:
  name:           'Azi Chen'
  #url:

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
